- name: Get artifacts and generate comment
  uses: actions/github-script@v6
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const run_id = context.payload.workflow_run.id;  // 실행 ID 가져오기
      const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
        owner: context.repo.owner,
        repo: context.repo.repo,
        run_id: run_id
      });
      
      let body = "Firmware for this pull request:\n";
      artifacts.data.artifacts.forEach(artifact => {
        body += `- [${artifact.name}](${artifact.archive_download_url})\n`;
      });
      
      const issue_number = context.payload.workflow_run.pull_requests[0].number;
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: issue_number,
        body: body
      });
